// src/features/Pricing/Constants/PricingConstants.ts
import { ApiBillingPlan } from '../Types/PricingTypes';

export const ENTERPRISE_TIER_TABS = [
  { label: 'Hybrid Multi-Brand', value: 'BOT' },
  { label: 'Restaurant Enterprise', value: 'RES' },
  { label: 'Retail Enterprise', value: 'RET' },
] as const;

export const FALLBACK_ENTERPRISE_PLANS: ApiBillingPlan[] = [
  // 1. Standalone POS Plans (from $6/day)
  {
    planId: 'cc377443-9132-9d5b-e49f-fcfa7a8e2ebf',
    planCode: 'pos-res-basic',
    planName: 'Standalone POS · Restaurant · Basic',
    displayName: 'Basic',
    planType: 'StandalonePos',
    flavour: 'RES',
    description: 'Basic tier of Standalone POS for single-outlet merchants.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 6.0,
    sortOrder: 1,
    activeSubscriberCount: 0,
    maxLocations: 1,
    maxTerminals: 1,
    marketingBullets: [
      'Single-terminal POS for one outlet — install on-premise and bill in minutes',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'All 23 core features and every payment method included',
    ],
  },
  {
    planId: '091a710c-c779-33b6-f48f-cb7213d69ab9',
    planCode: 'pos-res-pro',
    planName: 'Standalone POS · Pro',
    displayName: 'Pro',
    planType: 'StandalonePos',
    flavour: 'RES',
    description: 'Pro tier of Standalone POS for growing single-store operations.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 10.0,
    sortOrder: 11,
    activeSubscriberCount: 0,
    maxLocations: 1,
    maxTerminals: 3,
    marketingBullets: [
      'Up to 3 POS terminals and 500 products on one outlet',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Advance Inventory module on top of all 23 core features',
    ],
  },
  {
    planId: 'b7e09b6a-4d5c-208b-f315-9ea2e8ab7fe1',
    planCode: 'pos-res-adv',
    planName: 'Standalone POS · Advance',
    displayName: 'Advance',
    planType: 'StandalonePos',
    flavour: 'RES',
    description: 'Advance tier of Standalone POS with multi-till licensing.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 15.0,
    sortOrder: 21,
    activeSubscriberCount: 0,
    maxLocations: 2,
    maxTerminals: 5,
    marketingBullets: [
      'Up to 5 terminals across 2 outlets with 1,000 products',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Advance Inventory and Analytics modules included',
    ],
  },

  // 2. Cloud POS Plans (from $20/day)
  {
    planId: '1ad7bd7b-ecab-6fc3-ad66-7489125de1a4',
    planCode: 'cld-res-basic',
    planName: 'Standalone Cloud · Basic',
    displayName: 'Basic',
    planType: 'StandaloneCloud',
    flavour: 'RES',
    description: 'Dedicated cloud POS instance with web storefront.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 20.0,
    sortOrder: 101,
    activeSubscriberCount: 0,
    maxLocations: 2,
    maxTerminals: 4,
    marketingBullets: [
      'Your own isolated cloud instance with web storefront and 2 outlets',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Advance Inventory module plus all 23 core features',
    ],
  },
  {
    planId: '0fa01fcc-ac53-4e94-28cc-71bd676573a4',
    planCode: 'cld-res-pro',
    planName: 'Standalone Cloud · Pro',
    displayName: 'Pro',
    planType: 'StandaloneCloud',
    flavour: 'RES',
    description: 'High-speed cloud POS with online store ordering.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 25.0,
    sortOrder: 111,
    activeSubscriberCount: 0,
    maxLocations: 5,
    maxTerminals: 10,
    marketingBullets: [
      'Up to 5 outlets and 10 terminals with centralized menu management',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Online ordering website, CRM and marketing coupons included',
    ],
  },
  {
    planId: '2bce37b7-5f11-4775-8ceb-eb065b263914',
    planCode: 'cld-res-adv',
    planName: 'Standalone Cloud · Advance',
    displayName: 'Advance',
    planType: 'StandaloneCloud',
    flavour: 'RES',
    description: 'Full multi-outlet cloud network with central kitchen and inventory.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 30.0,
    sortOrder: 121,
    activeSubscriberCount: 0,
    maxLocations: 10,
    maxTerminals: 20,
    marketingBullets: [
      'Up to 10 outlets and 20 terminals across cities',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Multi-branch central kitchen, warehouse transfers and live reporting',
    ],
  },

  // 3. Hybrid Enterprise Cloud Plans (from $60/day)
  {
    planId: 'd6aa807d-7f24-6fbd-9f34-13680285f8b8',
    planCode: 'ent-bot-basic',
    planName: 'Enterprise Cloud · Restaurant + Retail · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    description: 'Managed enterprise cloud for up to 3 businesses and 15 outlets.',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 203,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'Run restaurant and retail terminals side by side on one licence',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: '74d8fc3b-2858-583d-20f7-0485bffee5ee',
    planCode: 'ent-bot-pro',
    planName: 'Enterprise Cloud · Restaurant + Retail · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 213,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'Run restaurant and retail terminals side by side on one licence',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: 'aba952a7-5ac3-1fbe-2eb4-93b8318c7335',
    planCode: 'ent-bot-adv',
    planName: 'Enterprise Cloud · Restaurant + Retail · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 223,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'Run restaurant and retail terminals side by side on one licence',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },

  // 2. Restaurant Enterprise Cloud
  {
    planId: '439cebde-fb45-5957-dcbc-e7889cfae152',
    planCode: 'ent-res-basic',
    planName: 'Enterprise Cloud · Restaurant · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 201,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: 'c28b0a35-5fc7-e5ff-d12e-820d7ec48b8a',
    planCode: 'ent-res-pro',
    planName: 'Enterprise Cloud · Restaurant · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 211,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: '5fa27409-5d81-9774-028c-a04699b92a61',
    planCode: 'ent-res-adv',
    planName: 'Enterprise Cloud · Restaurant · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 221,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },

  // 3. Retail Enterprise Cloud
  {
    planId: 'ba0ddd41-0d58-32ef-4de5-3a3e4ca72822',
    planCode: 'ent-ret-basic',
    planName: 'Enterprise Cloud · Retail · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 202,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: '9b6116f3-d2e0-6722-1663-1bb61722b9c7',
    planCode: 'ent-ret-pro',
    planName: 'Enterprise Cloud · Retail · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 212,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: '832aee36-e1a3-b4aa-f558-1c180def9174',
    planCode: 'ent-ret-adv',
    planName: 'Enterprise Cloud · Retail · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 222,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },
];
