// src/features/Pricing/Constants/PricingConstants.ts
import { ApiBillingPlan } from '../Types/PricingTypes';

export const ENTERPRISE_TIER_TABS = [
  { label: 'Hybrid Multi-Brand', value: 'BOT' },
  { label: 'Restaurant Enterprise', value: 'RES' },
  { label: 'Retail Enterprise', value: 'RET' },
] as const;

export const FALLBACK_ENTERPRISE_PLANS: ApiBillingPlan[] = [
  // 1. Hybrid Enterprise Cloud
  {
    planId: 'd6aa807d-7f24-6fbd-9f34-13680285f8b8',
    planCode: 'ent-bot-basic',
    planName: 'Enterprise Cloud · Restaurant + Retail · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 203,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'Run restaurant and retail terminals side by side on one licence',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: '74d8fc3b-2858-583d-20f7-0485bffee5ee',
    planCode: 'ent-bot-pro',
    planName: 'Enterprise Cloud · Restaurant + Retail · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 213,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'Run restaurant and retail terminals side by side on one licence',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: 'aba952a7-5ac3-1fbe-2eb4-93b8318c7335',
    planCode: 'ent-bot-adv',
    planName: 'Enterprise Cloud · Restaurant + Retail · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'BOT',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 223,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'Run restaurant and retail terminals side by side on one licence',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },

  // 2. Restaurant Enterprise Cloud
  {
    planId: '439cebde-fb45-5957-dcbc-e7889cfae152',
    planCode: 'ent-res-basic',
    planName: 'Enterprise Cloud · Restaurant · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 201,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: 'c28b0a35-5fc7-e5ff-d12e-820d7ec48b8a',
    planCode: 'ent-res-pro',
    planName: 'Enterprise Cloud · Restaurant · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 211,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: '5fa27409-5d81-9774-028c-a04699b92a61',
    planCode: 'ent-res-adv',
    planName: 'Enterprise Cloud · Restaurant · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'RES',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 221,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'Dine-in, counter, pickup, delivery and catering service channels',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },

  // 3. Retail Enterprise Cloud
  {
    planId: 'ba0ddd41-0d58-32ef-4de5-3a3e4ca72822',
    planCode: 'ent-ret-basic',
    planName: 'Enterprise Cloud · Retail · Basic',
    displayName: 'Basic',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 60.0,
    sortOrder: 202,
    activeSubscriberCount: 0,
    maxLocations: 15,
    maxTerminals: 30,
    marketingBullets: [
      'Managed enterprise cloud for up to 3 businesses and 15 outlets',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'Inventory, HR, Marketing and Analytics modules with bridge sync',
    ],
  },
  {
    planId: '9b6116f3-d2e0-6722-1663-1bb61722b9c7',
    planCode: 'ent-ret-pro',
    planName: 'Enterprise Cloud · Retail · Pro',
    displayName: 'Pro',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 100.0,
    sortOrder: 212,
    activeSubscriberCount: 0,
    maxLocations: 50,
    maxTerminals: 100,
    marketingBullets: [
      '10 businesses, 50 outlets and 100 terminals under one roof',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'All six advance modules included with online billing',
    ],
  },
  {
    planId: '832aee36-e1a3-b4aa-f558-1c180def9174',
    planCode: 'ent-ret-adv',
    planName: 'Enterprise Cloud · Retail · Advance',
    displayName: 'Advance',
    planType: 'EnterpriseCloud',
    flavour: 'RET',
    isActive: true,
    isPublic: true,
    isDeprecated: false,
    planPricePerDay: 175.0,
    sortOrder: 222,
    activeSubscriberCount: 0,
    maxLocations: 100,
    maxTerminals: 250,
    marketingBullets: [
      '25 businesses, 100 outlets and 250 terminals — our biggest footprint',
      'In-store billing with shipping, pickup and delivery fulfilment',
      'All six advance modules, 500 GB storage and 10 web storefronts',
    ],
  },
];
