import { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const host = process.env.NEXT_PUBLIC_APP_URL || 'https://www.quantix.com';
  const routes = [
    '',
    '/products',
    '/products/restaurant-pos',
    '/products/retail-pos',
    '/products/cloud-pos',
    '/products/enterprise-pos',
    '/products/websites',
    '/products/mobile-application',
    '/products/custom-service',
    '/solutions',
    '/solutions/fine-dining',
    '/solutions/quick-service',
    '/solutions/fast-casual',
    '/solutions/cafe-bakery',
    '/solutions/fashion-retail',
    '/solutions/grocery',
    '/solutions/electronics',
    '/solutions/franchise',
    '/features',
    '/features/smart-inventory',
    '/features/offline-registers',
    '/features/table-management',
    '/features/self-service-kiosk',
    '/features/qr-code-ordering',
    '/features/kitchen-display',
    '/features/delivery-management',
    '/features/marketing-loyalty',
    '/features/secure-payments',
    '/features/owner-app',
    '/features/menu-boards',
    '/integrations',
    '/integrations/stripe',
    '/integrations/authorize-net',
    '/integrations/square',
    '/integrations/paypal',
    '/integrations/doordash',
    '/integrations/uber-eats',
    '/pricing',
    '/resources',
    '/faq',
    '/help',
    '/blog',
    '/roi-calculator',
    '/downloads',
    '/status',
    '/enterprise-vs-standalone',
    '/about',
    '/careers',
    '/press',
    '/testimonials',
    '/sign-in',
    '/sign-up',
  ];

  return routes.map((route) => ({
    url: `${host}${route}`,
    lastModified: new Date(),
    changeFrequency: route === '' ? 'daily' : 'weekly',
    priority: route === '' ? 1.0 : route.startsWith('/products') ? 0.9 : 0.8,
  }));
}
