// src/features/CaseStudies/constants/defaultCaseStudies.ts
import { CaseStudyDto } from '../Types/CaseStudiesTypes';

export const DEFAULT_CASE_STUDIES: CaseStudyDto[] = [
  {
    id: "cs-1",
    slug: "krave-burger-co",
    title: "How Krave Scaled from 3 to 18 Locations with Zero Peak-Lunch Order Loss",
    companyName: "Krave Burger Co.",
    industry: "Quick Service (QSR)",
    challenge: "Peak lunch surges overwhelmed kitchen staff with lost paper slips and 18-minute ticket delays across fragmented registers.",
    solution: "Deployed Quantix digital Kitchen Display Systems (KDS) with color-coded course fire times and centralized 1-click cloud menu push.",
    result: "Achieved 0% ticket loss, cut turnaround times by 38%, and saved $42,000 in annual POS SaaS licensing fees.",
    statLabel: "Turnaround Speed",
    statValue: "+38%",
    createdAt: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "cs-2",
    slug: "fresh-market-retail",
    title: "Automating Real-Time Inventory & Shrinkage Across 24 Supermarkets",
    companyName: "The Fresh Market",
    industry: "Grocery & Retail",
    challenge: "Department managers spent 12 hours weekly doing manual inventory counts with recurring stockouts on top revenue SKUs.",
    solution: "Integrated Quantix Barcode Receiving with automated batch expiration warnings and supplier replenishment re-order thresholds.",
    result: "Reduced perishable inventory shrinkage by 65%, saved 14 hours of manager labor weekly, and eliminated holiday stockouts.",
    statLabel: "Shrinkage Cut",
    statValue: "-65%",
    createdAt: "2026-02-10T00:00:00.000Z",
  },
  {
    id: "cs-3",
    slug: "apex-hospitality-group",
    title: "Multi-Terminal Floor Management for 12 High-Volume Dining & Rooftop Venues",
    companyName: "Apex Hospitality Group",
    industry: "Hospitality & Bars",
    challenge: "Network drops on crowded rooftop terraces caused handheld terminals to spin and drop drink tabs during Friday peak hours.",
    solution: "Installed Quantix offline mesh registers with sub-200ms peer till synchronization and 1-tap pre-authorized card tab holding.",
    result: "Accelerated checkout velocity by 2.4x, maintained 99.99% uptime with zero downtime across 52 consecutive weekends.",
    statLabel: "Checkout Velocity",
    statValue: "2.4x",
    createdAt: "2026-03-01T00:00:00.000Z",
  },
  {
    id: "cs-4",
    slug: "trattoria-elegante",
    title: "Fine Dining Table Pacing & Split-Billing Modernization Across 4 Locations",
    companyName: "Trattoria Elegante",
    industry: "Fine Dining",
    challenge: "Complex split-bill payments and manual course firing slowed down table turnaround during Friday and Saturday dinner seatings.",
    solution: "Visual course pacing alerts synced directly with kitchen stations, and NFC pay-at-table mobile handhelds for frictionless check splitting.",
    result: "Increased table turnover velocity by 18%, shaved 8 minutes off diner wait times, and saved 32% on credit card processing fees.",
    statLabel: "Table Turn Velocity",
    statValue: "+18%",
    createdAt: "2026-03-10T00:00:00.000Z",
  },
];
